name: tutorial_flutter_redux_navigation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  go_router: ^14.3.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true
